version: '3.9'
services:
  backend:
    build: .
    ports:
      - "5501:5501"
    container_name: knh-visit-notify
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_NAME=$DB_NAME
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - TZ=Asia/Bangkok
    volumes:
      - .:/knh-visit-notify
    restart: always